### ISSUE TITLE
Button type 

### ISSUE THREAD

**Issue by codekennML** [Norserium/react-mobile-cropper#3]
Hi, 
I  am using formik for a multistep form and it navigates to the next page if there is a button that is specifically not marked with a type "button".
The rmc navigation buttons for flipping and rotating do not explicitly have a type and its causing a problem. 

Is there a way to resolve this, ofcourse i believe its a minor issue and i could open a pull request to this effect if that would be fine

**Comment by Norserium** [comment]
@codekennML, you are right. The type `button` set for buttons in `0.10.0`. Update to the latest version.

**Comment by codekennML** [comment]
Awesome. Thanks for the quick fix..You guys rock

**Comment by Norserium** [comment]
@codekennML, you are welcome!
