### ISSUE TITLE
Auto Zoom Behavior Enabled by Default on Mobile Cropper

### ISSUE THREAD

**Issue by moonbeam-dev** [Norserium/react-mobile-cropper#4]
Hello,

First of all, fantastic library for image cropping.  I am having good experience with it.

One thing that I noticed is that the mobile cropper has auto-zoom behavior enabled by default.  I know that the AutoZoom prop has been deprecated.  Is there any way to disable auto zoom behavior easily in react mobile cropper?

Thank you!

**Comment by Norserium** [comment]
@cl-moonventures, why do you want to disable auto zoom? 

This library is not designed to be flexible, it's designed to be ready-to-use, but there is the opportunity to add the possibility to redefine a postprocess algorithm. I just want to find out the reason and the desired result.

**Comment by moonbeam-dev** [comment]
@Norserium Ok, no worries. It is mainly preference. I agree that autozoom feature on mobile makes sense and will close.

Thank you again.
